# Site settings
title: Lauren Holter
email: laurentholter@gmail.com
url: http://laurenholter.com/
description: "Writer, Editor, Content Strategist"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  light-link: "#698291"
  links: '#bfdff1'

# Footer settings
# footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/laurenholter

# Build settings
markdown: kramdown
permalink: pretty
